### ISSUE TITLE
Fetch is not defined...

### ISSUE THREAD

**Issue by Ferm0494** [JonahGroendal/acme-easy#4]
Using client and it says fetch is not defined.

**Comment by JonahGroendal** [comment]
Are you using this package in node rather than in a browser? If so, adding
`global.fetch = require("node-fetch");`
To the top of your code file hould fix the problem. You will also need to `npm i node-fetch` of course

**Comment by Ferm0494** [comment]
After doing the steps I got
```
 uncaughtException
 caused exit: TypeError: WebCrypto is not a constructor
```

**Comment by Ferm0494** [comment]
Then after doing the following snippet.
`import { Crypto } from "node-webcrypto-ossl";`
`global.window.crypto = new Crypto();`

Getting TextEncoder is not defined.

**Comment by JonahGroendal** [comment]
@Ferm0494 you could try using https://www.npmjs.com/package/web-encoding
Then set global.TextEncoder and global.TextDecoder

**Comment by JonahGroendal** [comment]
@Ferm0494 let me know if that worked or if you have any more problems/questions. This package was designed to be used in a browser but it should work just fine on a node server as well with those polyfills.

Btw I didn't realize people were using this package but I see it's getting ~10 downloads per week. I'll be updating the dependencies to get rid of all those warnings on install.
